# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'GroopCam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroopCam

  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Kingfisher', '~> 5.0'
#  pod 'Stripe', '~> 15.0.1'
  pod 'Stripe/ApplePay'
  pod 'Alamofire', '~> 4.5'
  pod "BSImagePicker"
#  pod 'Stripe/ApplePay'

end

